#!/bin/bash

cp ~/.bash_profile ./home/.bash_profile
cp ~/.gitconfig ./home/.gitconfig
cp ~/.gitignore ./home/.gitignore
cp ~/.tmux.conf ./home/.tmux.conf
cp ~/.vimrc ./home/.vimrc
cp ~/.agignore ./home/.agignore
