#!/bin/bash
cp ~/.bash_profile ./home/.bash_profile
cp ~/.zshenv ./home/.zshenv
cp ~/.zshrc ./home/.zshrc
cp ~/.gitconfig ./home/.gitconfig
cp ~/.gitignore ./home/.gitignore
cp ~/.tmux.conf ./home/.tmux.conf
cp -r ~/.config/nvim ./home/.config/
cp ~/.agignore ./home/.agignore
