#!/bin/bash

cp ./home/.bash_profile ~/.bash_profile
cp ./home/.gitconfig ~/.gitconfig
cp ./home/.gitignore ~/.gitignore
cp ./home/.tmux.conf ~/.tmux.conf
cp ./home/.tmux/dev ~/.tmux/dev
cp ./home/.vimrc ~/.vimrc
cp ./home/.agignore ~/.agignore

echo "----------------------------------------------------------------------------------"
echo "| Ensure the following were run at some point on this machine:                   |"
echo "| git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim |"
echo "| Launch vim and run ':PluginInstall'                                            |"
echo "|--------------------------------------------------------------------------------|"
echo "| Programs:                                                                      |"
echo "| - the_silver_searcher                                                          |"
echo "| - tmux                                                                         |"
echo "| - vim                                                                          |"
echo "| - ruby                                                                         |"
echo "| - rvm                                                                          |"
echo "----------------------------------------------------------------------------------"

